name: PMD APEX Code Analysis

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
name: Review
on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened]
        branches: [main]
jobs:
    review:
        name: ReviewSource
        runs-on: 'ubuntu-latest'
        steps:
            - name: Code Review
              uses: packocz/sfdx-code-review-action@v0.3.0
              with:
                  source_path: ''"***.cls" "***.trigger" "***.js" "***.html" "***.page" "***.cmp" "***.component"'
                  reject_threshold: 1
                  max_comments: 20
                  category: '!Documentation'
                  engine: 'pmd, eslint'
                  dfa_setting: 'dfa'
                  github_token: ${{ secrets.Code_Review }}

jobs:
  pmd_analysis:
    name: Run PMD Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    
- name: Install PMD
      run: |
        wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.50.0/pmd-bin-6.50.0.zip
        unzip pmd-bin-6.50.0.zip
        export PATH=$PATH:pmd-bin-6.50.0/bin/

#    - name: Download PMD
 #     run: |
   #     wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.42.0/pmd-bin-6.42.0.zip
     #   unzip pmd-bin-6.42.0.zip
    
    - name: Run PMD Analysis
      run: |
        java -cp "pmd-bin-6.50.0/lib/*" net.sourceforge.pmd.PMD -d force-app/main/default/classes -R rulesets/apex/*.xml -reportfile pmd-report.txt

    - name: Upload PMD Report
      uses: actions/upload-artifact@v2
      with:
        name: pmd-report
        path: pmd-report.txt
